import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, ChevronRight, KeyRound, LayoutDashboard, MonitorCog, Play, TerminalSquare, Users } from "lucide-react";
import { api, Host, Job, login, Script, User } from "./api";
import { Button } from "./components/ui/button";

type View = "overview" | "hosts" | "users" | "scripts" | "jobs";
const nav: {id:View; label:string; icon:typeof Activity}[] = [{id:"overview",label:"概览",icon:LayoutDashboard},{id:"hosts",label:"机器",icon:MonitorCog},{id:"users",label:"用户与公钥",icon:Users},{id:"scripts",label:"脚本模板",icon:TerminalSquare},{id:"jobs",label:"执行记录",icon:Activity}];

export function App() {
  const [view,setView]=useState<View>("overview"), [authed,setAuthed]=useState(false), [password,setPassword]=useState(""), [error,setError]=useState("");
  const [hosts,setHosts]=useState<Host[]>([]), [users,setUsers]=useState<User[]>([]), [scripts,setScripts]=useState<Script[]>([]), [jobs,setJobs]=useState<Job[]>([]), [syncUser,setSyncUser]=useState<User|null>(null), [selected,setSelected]=useState<string[]>([]), [selectedScript,setSelectedScript]=useState("");
  const load=async()=>{ try { const [h,u,s,j]=await Promise.all([api<Host[]>("/hosts"),api<User[]>("/users"),api<Script[]>("/script-templates"),api<Job[]>("/jobs")]); setHosts(h);setUsers(u);setScripts(s);setJobs(j);setError(""); } catch(e){setError(e instanceof Error?e.message:"加载失败");} };
  useEffect(()=>{fetch("/api/auth/me",{credentials:"include"}).then(r=>{if(r.ok){setAuthed(true);load();}});},[]);
  if(!authed) return <main className="login"><section><p className="eyebrow">INTERNAL CONTROL PLANE</p><h1>账户管理控制台</h1><p>在确认前不改变任何机器。</p><form onSubmit={async e=>{e.preventDefault();try{await login(password);setAuthed(true);load();}catch(err){setError(err instanceof Error?err.message:"登录失败");}}}><label>管理员密码<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><Button type="submit">进入控制台 <ChevronRight size={16}/></Button>{error&&<small className="error">{error}</small>}</form></section></main>;
  const addHost=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api<Host>("/hosts",{method:"POST",body:JSON.stringify({name:f.get("name"),address:f.get("address"),port:Number(f.get("port")||22),ssh_user:f.get("ssh_user")||"root",tags:String(f.get("tags")||"").split(",")})});e.currentTarget.reset();load();};
  const addUser=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api<User>("/users",{method:"POST",body:JSON.stringify({username:f.get("username"),display_name:f.get("display_name")})});e.currentTarget.reset();load();};
  const addScript=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api<Script>("/script-templates",{method:"POST",body:JSON.stringify({name:f.get("name"),description:f.get("description"),body:f.get("body")})});e.currentTarget.reset();load();};
  const testHost=async(host:Host)=>{const result=await api<{requires_confirmation:boolean;fingerprint:string|null;error:string|null}>(`/hosts/${host.id}/test`,{method:"POST"});if(result.requires_confirmation&&result.fingerprint&&window.confirm(`确认主机指纹？\n${result.fingerprint}`))await api(`/hosts/${host.id}/confirm-fingerprint`,{method:"POST",body:JSON.stringify({fingerprint:result.fingerprint})});if(result.error)setError(result.error);load();};
  const addKey=async(user:User)=>{const key=window.prompt(`为 ${user.username} 粘贴 SSH 公钥`);if(key)await api(`/users/${user.id}/keys`,{method:"POST",body:JSON.stringify({public_key:key})});load();};
  const preview=async()=>{if(!syncUser||!selected.length){setError("请至少勾选一台可连接机器");return;} const job=await api<Job>("/jobs/preview",{method:"POST",body:JSON.stringify({user_id:syncUser.id,host_ids:selected,script_template_id:selectedScript||null})});setJobs([job,...jobs]);setSyncUser(null);setView("jobs");};
  const content= view==="overview"?<Overview hosts={hosts} users={users} jobs={jobs}/>:view==="hosts"?<><InlineForm title="接入机器" onSubmit={addHost} fields={["name:名称","address:IP 或 FQDN","port:端口","ssh_user:SSH 用户","tags:标签，逗号分隔"]}/><Table rows={hosts} columns={["name","address","ssh_user","tags","status"]} action={(h:Host)=><Button onClick={()=>testHost(h)}>测试连接</Button>}/></>:view==="users"?<><InlineForm title="创建 Linux 用户" onSubmit={addUser} fields={["username:用户名","display_name:显示名"]}/><Table rows={users} columns={["username","display_name","shell","home","enabled"]} action={(u:User)=><><Button className="quiet" onClick={()=>addKey(u)}><KeyRound size={14}/>公钥</Button><Button onClick={()=>{setSyncUser(u);setSelected([])}}><Play size={14}/>同步</Button></>}/></>:view==="scripts"?<><ScriptForm title="新增后置脚本" onSubmit={addScript}/><Table rows={scripts} columns={["name","description","version","enabled"]}/></>:<Jobs jobs={jobs} onExecute={async id=>{const job=await api<Job>(`/jobs/${id}/execute`,{method:"POST"});setJobs(jobs.map(j=>j.id===id?job:j));}}/>;
  return <div className="layout"><aside><div className="brand"><KeyRound size={20}/><span>ACC/CTL</span></div>{nav.map(n=>{const Icon=n.icon;return <button key={n.id} className={view===n.id?"nav active":"nav"} onClick={()=>setView(n.id)}><Icon size={17}/>{n.label}</button>})}</aside><main className="workspace"><header><div><p className="eyebrow">单管理员 · 内网控制面</p><h1>{nav.find(n=>n.id===view)?.label}</h1></div><Button className="quiet" onClick={load}>刷新</Button></header>{error&&<p className="error">{error}</p>}{content}{syncUser&&<section className="panel sync"><h2>同步 {syncUser.username}</h2><p>仅勾选本次需要变更的机器，预检成功后还需再次确认。</p>{hosts.filter(h=>h.status==="reachable").map(h=><label className="check" key={h.id}><input type="checkbox" checked={selected.includes(h.id)} onChange={e=>setSelected(e.target.checked?[...selected,h.id]:selected.filter(id=>id!==h.id))}/>{h.name} <small>{h.address}</small></label>)}<label className="script-choice">后置脚本<select value={selectedScript} onChange={e=>setSelectedScript(e.target.value)}><option value="">不执行后置脚本</option>{scripts.filter(script=>script.enabled).map(script=><option key={script.id} value={script.id}>{script.name} · v{script.version}</option>)}</select></label><div><Button onClick={preview}>执行预检</Button><Button className="quiet" onClick={()=>setSyncUser(null)}>取消</Button></div></section>}</main></div>;
}
function Overview({hosts,users,jobs}:{hosts:Host[];users:User[];jobs:Job[]}){return <><div className="metrics"><Metric label="机器" value={hosts.length}/><Metric label="可连接" value={hosts.filter(h=>h.status==="reachable").length}/><Metric label="用户" value={users.length}/><Metric label="任务" value={jobs.length}/></div><section className="panel"><h2>最近任务</h2><Table rows={jobs.slice(0,6)} columns={["id","state","created_at"]}/></section></>}
function Metric({label,value}:{label:string;value:number}){return <section className="metric"><span>{label}</span><strong>{value}</strong></section>}
function InlineForm({title,onSubmit,fields}:{title:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;fields:string[]}){return <form className="panel inline" onSubmit={onSubmit}><h2>{title}</h2><div>{fields.map(field=>{const [name,label]=field.split(":");return <label key={name}>{label}<input name={name} required={name!=="tags"&&name!=="port"}/></label>})}<Button type="submit">保存</Button></div></form>}
function ScriptForm({onSubmit,title="新增后置脚本"}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;title?:string}){return <form className="panel inline" onSubmit={onSubmit}><h2>{title}</h2><div><label>名称<input name="name" required/></label><label>说明<input name="description"/></label><label className="wide">脚本正文<textarea name="body" required rows={4}/></label><Button type="submit">保存模板</Button></div></form>}
function Table({rows,columns,action}:{rows:any[];columns:string[];action?:(r:any)=>React.ReactNode}){return <section className="panel table"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}{action&&<th/>}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i}>{columns.map(c=><td key={c}>{Array.isArray(row[c])?row[c].join(", "):String(row[c]??"-")}</td>)}{action&&<td>{action(row)}</td>}</tr>)}</tbody></table>{!rows.length&&<p className="empty">暂无记录</p>}</section>}
function Jobs({jobs,onExecute}:{jobs:Job[];onExecute:(id:string)=>void}){return <Table rows={jobs} columns={["id","state","created_at"]} action={(j:Job)=>j.state==="ready_to_confirm"?<Button onClick={()=>onExecute(j.id)}><Play size={14}/>确认执行</Button>:null}/>}
